<div class="navbar navbar-custom">
    <div class="navbar-inner navbar-inner-custom" id="header">
        <div class="container container-main">
            <!-- <span class="icon-plane-top pull-left"></span> -->
            <h2 class="brand brand-custom"><?php echo Enum_Lang::getPageText('system', 'systemName'); ?></h2>
            <div class="btn-group pull-right" style="margin-left: 20px;">
                <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    <?php echo $headerInfo['userName']; ?><span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li><a href="/Login/logout"><?php echo Enum_Lang::getPageText('system', 'logout'); ?></a></li>
                </ul>
            </div>
            <ul class="nav pull-right">
                <li class="divider-vertical divider-vertical-custom"></li>
                <li><p class="navbar-text text-custom"><?php echo Enum_Lang::getPageText('system', 'welcomeMsg'); ?></p></li>
            </ul>
        </div>
    </div>
</div> 
