<div class="navbar navbar-custom">
    <div class="navbar-inner navbar-inner-custom" id="header">
        <div class="container container-main">
            <!-- <span class="icon-plane-top pull-left"></span> -->
            <h2 class="brand brand-custom"><a href="/" style="text-decoration: none; color: white;"><?php echo Enum_Lang::getPageText('system', 'systemName'); ?></a></h2>
            <div class="btn-group pull-right" style="margin-left: 20px;">
                <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    <?php echo $headerInfo['userName']; ?><span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li><a href="/Login/logout"><?php echo Enum_Lang::getPageText('system', 'logout'); ?></a></li>
                </ul>
            </div>
            <ul class="nav pull-right">
                <li class="divider-vertical divider-vertical-custom"></li>
                <li><p class="navbar-text text-custom"><?php echo Enum_Lang::getPageText('system', 'welcomeMsg'); ?></p></li>
            </ul>

            <div class="btn-group pull-right" style="margin-left: 10px">
                <button id="changeLanguageButton" data-now="<?php echo $headerInfo['useLanguage']; ?>" class="btn dropdown-toggle" data-toggle="dropdown"
                        data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>">
                    <?php echo $headerInfo['useLanguageShow']; ?><span class="caret"></span>
                </button>
                <ul class="dropdown-menu" id="languageList">
                    <li op="changeLanguage" data-language="<?php echo Enum_Lang::LANG_KEY_CHINESE ?>"><a href="javascrip:;">中文</a></li>
                    <li class="divider"></li>
                    <li op="changeLanguage" data-language="<?php echo Enum_Lang::LANG_KEY_ENGLISH ?>"><a href="javascrip:;">English</a></li>
                </ul>
            </div>

            <?php
            if (!empty($userHotelList)) {
            ?>
            <div class="btn-group pull-right" id="changeHotel" style="margin-left: 20px;">
                <button class="btn dropdown-toggle" data-toggle="dropdown" data-now="<?php echo $userHotel['id'];?>"
                        data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>">
                    <?php echo $userHotel['name']; ?><span class="caret"></span>
                </button>
                <?php
                echo "<ul class='dropdown-menu'>";
                foreach ($userHotelList as $hotel) {
                    $option = sprintf("<li op='changeHotel' data-hotelid='%s'><a href='javascript:;'>%s</a></li>\n", $hotel['id'], $hotel['name']);
                    echo $option;
                }
                echo "</ul></div>";
                }
                ?>
            </div>
    </div>
</div> 
