<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'commentList'); ?>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/comment/list_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('comment', 'userid'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('comment', 'roomno'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('comment', 'fullname'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('comment', 'status'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('comment', 'datatitle'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('comment', 'createtime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('comment', 'ip'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('system', 'option'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/comment/list_edit.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        listUrl: '/commentajax/getList',
        updateUrl: '/commentajax/updateComment',
    };
</script>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/comment/list.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="userid" data-value="{{info.userid}}">{{info.userid}}</td>
        <td type="roomno" data-value="{{info.roomno}}">{{info.roomno}}</td>
        <td type="fullname" data-value="{{info.fullname}}">{{info.fullname}}</td>
        <td type="status" data-value="{{info.status}}">{{info.statusShow}}</td>
        <td type="datatitle" data-value="{{info.datatitle}}">{{info.datatitle}}</td>
        <td type="createtime" data-value="{{info.createtime}}">{{info.createtime}}</td>
        <td type="ip" data-value="{{info.ip}}">{{info.ip}}</td>
        <td type="value" data-value="{{info.value}}" style="display:none;"></td>
        <td>
            <button op="editDataOne" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}"><?php echo Enum_Lang::getPageText('system', 'view'); ?></button>
        </td>
    </tr>
    {{/each}}
</script>
