<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title><?php echo $hotelName; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/bootstrap.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/al_resize.css"/>
    <script src="<?php echo $webConfig['imgDomain']; ?>js/lib/jquery-1.11.1.min.js" type="text/javascript"></script>
    <script src="<?php echo $webConfig['imgDomain']; ?>js/lib/bootstrap.min.js" type="text/javascript"></script>
    <script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_ajax.js"></script>
    <script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_alert.js"></script>
    <script src="<?php echo $webConfig['imgDomain']; ?>js/common/modalfix.js" type="text/javascript"></script>
    <script src="<?php echo $webConfig['imgDomain']; ?>js/common/switch_hotel.js" type="text/javascript"></script>
    <link href="<?php echo $webConfig['imgDomain']; ?>css/css.css" rel="stylesheet">
    <link rel="icon" href="data:;base64,=">
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/bootstrap.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/reset.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/style.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/sign.css"/>


</head>
<body id="login">
<div id="login-wrapper" class="png_bg">
    <?php include(__DIR__ . '/lang.phtml') ?>
    <div id="login-top">
        <h1><?php echo Enum_Lang::getPageText('nav', 'signSystem'); ?></h1>
    </div>
    <!-- End #logn-top -->

    <div style="padding: 0 20%; color: white">

        <form class="form-horizontal" method="POST" action="/sign/dosign" id="sign-detail">
            <input type="hidden" value="<?php echo $category_id;?>" name="type">
            <fieldset>
                <div id="info-detail">
                    <div class="control-group">
                        <label class="control-label">No. of persons(人数)</label>
                        <div class="controls">
                            <input type="number" class="input-xlarge" name="num"/>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Lock No.(锁号码)</label>
                        <div class="controls">
                            <input type="text" class="input-xlarge" name="lock" placeholder="Optional(选填)"/>
                        </div>
                    </div>

                    <div class="control-group time-box">
                        <label class="control-label">Start Time(开始时间)：</label>
                        <div class="controls" style="color: black">
                            <input name="start_time" type="datetime-local" value=''/>
                            <button type="button" class="time-button btn-primary"><?php echo Enum_Lang::getPageText('system', 'confirm'); ?></button>
                        </div>
                    </div>

                    <div class="control-group time-box">
                        <label class="control-label">End Time(结束时间)：</label>

                        <div class="controls" style="color: black">
                            <input name="end_time" type="datetime-local" value=''/>
                            <button type="button" class="time-button btn-primary"><?php echo Enum_Lang::getPageText('system', 'confirm'); ?></button>
                        </div>
                    </div>

                    <div class="control-group">
                        <!-- Multiple Checkboxes -->

                        <table id="gym-container">
                            <?php
                            $i = 0;
                            foreach ($items as $row) {
                                if ($i % 3 == 0) {
                                    echo '<tr>';
                                }
                                $output = sprintf('<td><label class="checkbox inline gym-checkbox">
                                <input type="checkbox" value="%1$s" name="items[]"> %2$s
                            </label></td>', $row['id'], $row['title']);
                                echo $output;
                                if ($i % 3 == 2) {
                                    echo '</tr>';
                                }
                                $i++;
                            }
                            ?>
                        </table>
                    </div>


                    <div class="control-group" style="text-align: center">
                        <button type="button" class="btn-primary btn-large option"><?php echo Enum_Lang::getPageText('system', 'confirm'); ?></button>
                        <a href="/sign/index?hotelid=<?php echo $hotelid; ?>">
                            <button type="button" class="btn-primary btn-large"><?php echo Enum_Lang::getPageText('system', 'cancel'); ?></button>
                        </a>
                    </div>

                </div>


                <div id="login-detail" style="display: none">
                    <?php
                    if (isset($altPropertyId)) {
                        ?>
                        <div class="control-group">
                            <label class="control-label" for="propertyid">Property(物业): </label>
                            <div class="controls">
                                <select class="input-xlarge" name="propertyid" autocomplete="off">
                                    <option value="<?php echo $propertyId; ?>"
                                            selected><?php echo $hotelName; ?></option>
                                    <option value="<?php echo $altPropertyId; ?>"><?php echo $altHotelName; ?></option>
                                </select>
                            </div>
                            <div style="clear: both"></div>
                        </div>
                        <?php
                    }
                    ?>
                    <div class="control-group">
                        <!-- Text input-->
                        <label class="control-label" for="room">Room No.(房间号): </label>
                        <div class="controls">
                            <input type="text" placeholder="" class="input-xlarge" name="room" autocomplete="off">
                        </div>
                    </div>

                    <div class="control-group">

                        <!-- Text input-->
                        <label class="control-label" for="lastname">Last Name(姓): </label>
                        <div class="controls">
                            <input type="text" placeholder="" class="input-xlarge" name="lastname" autocomplete="off">
                        </div>
                    </div>
                    <div class="control-group" style="text-align: center">
                        <a>
                            <button type="submit" class="btn-primary btn-large submit"><?php echo Enum_Lang::getPageText('system', 'confirm'); ?></button>
                        </a>
                        <a href="/sign/index?hotelid=<?php echo $hotelid; ?>">
                            <button type="button" class="btn-primary btn-large"><?php echo Enum_Lang::getPageText('system', 'cancel'); ?></button>
                        </a>
                    </div>
                    <input type="hidden" name="hotelid" value="<?php echo $hotelid; ?>">
                </div>

                <input type="reset" style="display: none"/>


            </fieldset>
        </form>
    </div>
</div>
<!-- End #login-wrapper -->
<script src="<?php echo $webConfig['imgDomain']; ?>js/sign/sign.js"></script>
</body>
</html>
