<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title><?php echo Enum_Lang::getPageText('system', 'systemName'); ?></title>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/bootstrap.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/reset.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/style.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/datetimepicker.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/sign.css"/>


</head>
<body id="login">
<div id="login-wrapper" class="png_bg">
    <div id="login-top">
        <h1><?php echo Enum_Lang::getPageText('nav', 'signSystem'); ?></h1>
    </div>
    <!-- End #logn-top -->

    <div style="padding: 0 25%; color: white">

        <form class="form-horizontal" method="POST" action="/sign/dosign" id="sign-detail">
            <fieldset>

                <div id="info-detail">
                    <div class="control-group">
                        <label class="control-label">No. of persons(人数)</label>
                        <div class="controls">
                            <input type="number" class="input-xlarge" name="num"/>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Lock No.</label>
                        <div class="controls">
                            <input type="text" class="input-xlarge" name="lock"/>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">开始时间：</label>
                        <div class="controls" style="color: black">
                            <input name="start_time" type="text" class="form-control input-medium datetimepicker"
                                   value=''/>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">结束时间：</label>

                        <div class="controls" style="color: black">
                            <input name="end_time" type="text" class="form-control input-medium datetimepicker"
                                   value=''/>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"></label>

                        <!-- Multiple Checkboxes -->
                        <div class="controls">
                            <?php
                            foreach ($gyms as $name => $key) {
                                $output = sprintf('<label class="checkbox inline gym-checkbox">
                                <input type="checkbox" value="1" name="%s"> %s
                            </label>', $key, $name);
                                echo $output;
                            }
                            ?>
                        </div>


                    </div>

                    <div class="control-group" style="text-align: center">
                        <button type="button" class="btn-success option">确定</button>
                        <a href="/sign/index">
                            <button type="button" class="btn-danger">取消</button>
                        </a>
                    </div>

                </div>


                <div id="login-detail" style="display: none">
                    <div class="control-group">
                        <!-- Text input-->
                        <label class="control-label" for="room">Room No.(房间号): </label>
                        <div class="controls">
                            <input type="text" placeholder="" class="input-xlarge" name="room" autocomplete="off">
                        </div>
                        <div style="clear: both"></div>
                    </div>

                    <div class="control-group">

                        <!-- Text input-->
                        <label class="control-label" for="lastname">Last Name(姓): </label>
                        <div class="controls">
                            <input type="text" placeholder="" class="input-xlarge" name="lastname" autocomplete="off">
                        </div>
                    </div>
                    <div class="control-group" style="text-align: center">
                        <a>
                            <button type="submit" class="btn-success submit">确定</button>
                        </a>
                        <a href="/sign/index">
                            <button type="button" class="btn-danger">取消</button>
                        </a>
                    </div>
                </div>

                <input type="reset" style="display: none"/>


            </fieldset>
        </form>
    </div>
</div>
<!-- End #login-wrapper -->
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/jquery-1.11.1.min.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/bootstrap-datetimepicker.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/bootstrap-datetimepicker.zh-CN.js"
        type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/datatimepicker.config.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/sign/sign.js"></script>
</body>
</html>
