<!DOCTYPE html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <title><?php echo Enum_Lang::getPageText('system', 'systemName'); ?></title>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/bootstrap.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/reset.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/style.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/sign.css"/>


</head>
<body id="login">
<div id="login-wrapper" class="png_bg">
    <div id="login-top">
        <h1><?php echo Enum_Lang::getPageText('nav', 'signSystem'); ?></h1>
    </div>
    <!-- End #logn-top -->

    <div style="padding: 0 25%; color: white">

        <form class="form-horizontal" method="POST" action="/sign/dosign" id="sign-detail">
            <input type="hidden" value="<?php echo $category_id;?>" name="type">
            <fieldset>
                <div id="info-detail">
                    <div class="control-group">
                        <label class="control-label">No. of persons(人数)</label>
                        <div class="controls">
                            <input type="number" class="input-xlarge" name="num"/>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Lock No.(锁号码)</label>
                        <div class="controls">
                            <input type="text" class="input-xlarge" name="lock" placeholder="Optional(选填)"/>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Start Time(开始时间)：</label>
                        <div class="controls" style="color: black">
                            <input name="start_time" type="datetime-local" value=''/>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">End Time(结束时间)：</label>

                        <div class="controls" style="color: black">
                            <input name="end_time" type="datetime-local" value=''/>
                        </div>
                    </div>

                    <div class="control-group">
                        <!-- Multiple Checkboxes -->

                        <table id="gym-container">
                            <?php
                            $i = 0;
                            foreach ($items as $row) {
                                if ($i % 3 == 0) {
                                    echo '<tr>';
                                }
                                $output = sprintf('<td><label class="checkbox inline gym-checkbox">
                                <input type="checkbox" value="%1$s" name="items[]"> %2$s
                            </label></td>', $row['id'], $row['title']);
                                echo $output;
                                if ($i % 3 == 2) {
                                    echo '</tr>';
                                }
                                $i++;
                            }
                            ?>
                        </table>
                    </div>


                    <div class="control-group" style="text-align: center">
                        <button type="button" class="btn-primary btn-large option"><?php echo Enum_Lang::getPageText('system', 'confirm'); ?></button>
                        <a href="/sign/index">
                            <button type="button" class="btn-primary btn-large"><?php echo Enum_Lang::getPageText('system', 'cancel'); ?></button>
                        </a>
                    </div>

                </div>


                <div id="login-detail" style="display: none">
                    <div class="control-group">
                        <!-- Text input-->
                        <label class="control-label" for="room">Room No.(房间号): </label>
                        <div class="controls">
                            <input type="text" placeholder="" class="input-xlarge" name="room" autocomplete="off">
                        </div>
                        <div style="clear: both"></div>
                    </div>

                    <div class="control-group">

                        <!-- Text input-->
                        <label class="control-label" for="lastname">Last Name(姓): </label>
                        <div class="controls">
                            <input type="text" placeholder="" class="input-xlarge" name="lastname" autocomplete="off">
                        </div>
                    </div>
                    <div class="control-group" style="text-align: center">
                        <a>
                            <button type="submit" class="btn-primary btn-large submit"><?php echo Enum_Lang::getPageText('system', 'confirm'); ?></button>
                        </a>
                        <a href="/sign/index">
                            <button type="button" class="btn-primary btn-large"><?php echo Enum_Lang::getPageText('system', 'cancel'); ?></button>
                        </a>
                    </div>
                </div>

                <input type="reset" style="display: none"/>


            </fieldset>
        </form>
    </div>
</div>
<!-- End #login-wrapper -->
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/jquery-1.11.1.min.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/sign/sign.js"></script>
</body>
</html>
