<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <title><?php echo Enum_Lang::getPageText('system', 'systemName'); ?></title>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/bootstrap.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/reset.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/style.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/sign.css"/>
</head>
<body id="login">
<div id="login-wrapper" class="png_bg">
    <div id="login-top">
        <h1><?php echo Enum_Lang::getPageText('nav', 'signSystem'); ?></h1>
    </div>
    <!-- End #logn-top -->
    <div id="signBox">
        <?php
        $template = '<div id="category%1$s" class="category %4$s">
            <a href="/sign/item?id=%1$s">
                <img class="img2" src="%2$s" alt="" width="200" height="100"/>
            </a>
            <a href="/sign/item?id=%1$s">
                <button class="btn-primary btn-large">%3$s</button>
            </a>
        </div>';
        $index = 0;
        foreach ($categories as $category) {
            $index++;
            $class = ($index % 2 == 0 ? 'even' : 'odd');
            $output = sprintf($template, $category['id'], $category['pic'], $category['title'], $class);
            echo $output;
        }
        ?>
    </div>
    <!-- End #login-content -->
</div>
<!-- End #login-wrapper -->
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/jquery-1.11.1.min.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/bootstrap.min.js" type="text/javascript"></script>

</body>
</html>
