<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title><?php echo Enum_Lang::getPageText('system', 'systemName'); ?></title>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/bootstrap.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/reset.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/style.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/sign.css"/>
</head>
<body id="login">
<div id="login-wrapper" class="png_bg">
    <div id="login-top">
        <h1><?php echo Enum_Lang::getPageText('system', 'signSystem'); ?></h1>
    </div>
    <!-- End #logn-top -->
    <div id="signBox">
        <div id="canteen">
            <a href="/sign/swimming">
                <img class="img2" src="<?php echo $webConfig['imgDomain']; ?>img/sign/swimming-pool.jpg" alt=""
                     width="200" height="100"/>
            </a>
            <a href="/sign/swimming">
                <button class="btn-primary btn-large">游泳池</button>
            </a>
        </div>
        <div id="gym">
            <a href="/sign/gym">
                <img class="img2" src="<?php echo $webConfig['imgDomain']; ?>img/sign/gym.jpg" alt="" width="200"
                     height="100"/>
            </a>
            <a href="/sign/gym">
                <button class="btn-primary btn-large">健身房</button>
            </a>
        </div>
        <div style="clear: both"></div>
    </div>
    <!-- End #login-content -->
</div>
<!-- End #login-wrapper -->
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/jquery-1.11.1.min.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/bootstrap.min.js" type="text/javascript"></script>

</body>
</html>
