<div class="dropdown btn-group pull-right" style="margin: 10px;">
    <button id="changeLanguageButton" data-now="<?php echo $headerInfo['useLanguage']; ?>"
            class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
            data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>">
        <?php echo $switchLang; ?><span class="caret"></span>
    </button>
    <ul class="dropdown-menu" id="languageList">
        <li op="changeLanguage" data-language="<?php echo Enum_Lang::LANG_KEY_CHINESE ?>"><a href="#">中文</a>
        </li>
        <li class="divider"></li>
        <li op="changeLanguage" data-language="<?php echo Enum_Lang::LANG_KEY_ENGLISH ?>"><a href="#">English</a>
        </li>
    </ul>
</div>