<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/datetimepicker.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'signReport'); ?>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/sign/report_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('sign', 'signDate'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('sign', 'type'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('sign', 'roomNo'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('sign', 'lastName'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('sign', 'num'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('sign', 'lockNo'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('sign', 'startTime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('sign', 'endTime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('sign', 'sports'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        listUrl: '/sign/getSignList',
    };
</script>

<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/bootstrap-datetimepicker.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/bootstrap-datetimepicker.zh-CN.js"
        type="text/javascript"></script>
<script type="application/javascript">
    var datatimepickerConfig = {
        language: 'zh-CN',
        format: 'yyyy-mm-dd hh:ii:ss',
        autoclose: true,
        todayBtn: true,
        weekStart: 1,
        minView: 0,
        startView: 1,
        endDate: new Date()
    };
    $("input.datetimepicker").datetimepicker(datatimepickerConfig);
</script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/sign/report.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>

        <td type="created_at" data-value="{{info.created_at}}">{{info.created_at}}</td>
        <td type="type" data-value="{{info.type}}">{{info.type}}</td>

        <td type="room_no" data-value="{{info.room_no}}">{{info.room_no}}</td>
        <td>{{info.lastname}}</td>
        <td>{{info.num}}</td>
        <td type="lock_no" data-value="{{info.count}}">{{info.lock_no}}</td>
        <td type="start_time" data-value="{{info.statusid}}">{{info.start_time}}</td>
        <td type="end_time" data-value="{{info.adminid}}">{{info.end_time}}</td>
        <td type="sports" data-value="{{info.memo}}">{{info.sports}}</td>
    </tr>
    {{/each}}
</script>
