<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'showingOrder'); ?>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/showing/order_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('showing', 'ORDERNAME'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('showing', 'ORDERPHONE'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('showing', 'CREATETIME'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('showing', 'ORDERSTATUS'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('showing', 'ADMIN'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        listUrl: '/showingajax/getOrderList',
    };
</script>

<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/showing/order.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="name" data-value="{{info.name}}">{{info.name}}</td>
        <td type="phone" data-value="{{info.phone}}">{{info.phone}}</td>
        <td type="createtime" data-value="{{info.createtime}}">{{info.createtime}}</td>
        <td type="status" data-value="{{info.status}}">{{info.status}}</td>
        <td type="admin" data-value="{{info.admin}}">{{info.admin}}</td>
    </tr>
    {{/each}}
</script>
