<div class="modal hide fade yulong" id="resEditor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo Enum_Lang::getPageText('room', 'roomTypeResEdiTtitle'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="resEditorList">
                    <?php foreach ($resList as $key => $res) { ?>
                        <div class="control-group" op="editFiled">
                            <label class="control-label" for="edit_typeRes<?php echo $key; ?>"><?php echo $res['name_lang1']; ?>：</label>
                            <div class="controls">
                                <input type="checkbox" op="edit_typeRes" id="edit_typeRes<?php echo $key; ?>" value="<?php echo $res['id']; ?>"
                                       data-title="<?php echo $res['name_lang1']; ?>">
                            </div>
                        </div>
                    <?php } ?>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveRes" data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>"><?php echo Enum_Lang::getPageText('system', 'save'); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'><?php echo Enum_Lang::getPageText('system', 'close'); ?></button>
            </div>
        </div>
    </div>
</div>
