<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'ROOMLIST'); ?>
                        <button id="createData" class="btn btn-info" style="margin-left: 5px;" type="button" data-toggle="modal" data-target="#editor"><?php echo Enum_Lang::getPageText('system', 'create'); ?>
                        </button>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/room/room_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('room', 'roomNo'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('room', 'typeTitle'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('room', 'roomFloor'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('room', 'roomSize'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('room', 'lastUserFullName'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('room', 'lastLoginTime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('room', 'createtime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('system', 'option'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/room/room_edit.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        checkParams: '<?php echo json_encode(Enum_Room::getRoomMustInput());?>',
        listUrl: '/roomajax/getRoomList',
        createUrl: '/roomajax/createRoom',
        updateUrl: '/roomajax/updateRoom'
    };
</script>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/zh-CN.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/room/room.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="room" data-value="{{info.room}}">{{info.room}}</td>
        <td type="typeid" data-value="{{info.typeid}}">{{info.typeShow}}</td>
        <td type="floor" data-value="{{info.floor}}">{{info.floorShow}}</td>
        <td type="size" data-value="{{info.size}}">{{info.size}}</td>
        <td type="fullname" data-value="{{info.lastUser.fullname}}">{{info.lastUser.fullname}}</td>
        <td type="lastUserFullName" data-value="{{info.lastUser.lastLoginTime}}">{{info.lastUser.lastLoginTime}}</td>
        <td type="createtime">{{info.createtime}}</td>
        <td>
            <button op="editDataOne" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}"><?php echo Enum_Lang::getPageText('system', 'edit'); ?></button>
        </td>
    </tr>
    {{/each}}
</script>
