<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'roomType'); ?>
                        <button id="createData" class="btn btn-info" style="margin-left: 5px;" type="button"
                                data-toggle="modal" data-target="#editor"><?php echo Enum_Lang::getPageText('system', 'create'); ?>
                        </button>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/room/roomType_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('room', 'typeTitle'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('room', 'typeSize'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('room', 'typeBed'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('room', 'roomCount'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('room', 'typePanoramic'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('room', 'pic'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('room', 'createtime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('system', 'option'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/room/roomType_edit.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/room/roomType_res.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        checkParams: '<?php echo json_encode(Enum_Room::getRoomTypeMustInput());?>',
        listUrl: '/roomajax/getRoomTypeList',
        createUrl: '/roomajax/createRoomType',
        updateUrl: '/roomajax/updateRoomType',
    };
</script>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/zh-CN.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/room/roomType.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="titleLang1" data-value="{{info.titleLang1}}">{{info.titleLang1}}</td>
        <td type="size" data-value="{{info.size}}">{{info.size}}</td>
        <td type="bedtypeLang1" data-value="{{info.bedtypeLang1}}">{{info.bedtypeLang1}}</td>
        <td type="roomcount" data-value="{{info.roomcount}}">{{info.roomcount}}</td>
        <td type="panoramic" data-value="{{info.panoramic}}">
            {{if info.panoramic}}
            <a href="{{info.panoramic}}" target="_blank">
                {{info.panoramic}}
            </a>
            {{/if}}
        </td>
        <td type="pic" data-value="{{info.pic}}">
            {{if info.pic}}
            <a href="{{info.pic}}" target="_blank">
                <img src="{{info.pic}}" style="max-width: 100px;max-height: 100px;"/>
            </a>
            {{/if}}
        </td>
        <td type="createtime">{{info.createtime}}</td>
        <td type="titleLang2" data-value="{{info.titleLang2}}" style="display: none;"></td>
        <td type="titleLang3" data-value="{{info.titleLang3}}" style="display: none;"></td>
        <td type="bedtypeLang2" data-value="{{info.bedtypeLang2}}" style="display: none;"></td>
        <td type="bedtypeLang3" data-value="{{info.bedtypeLang3}}" style="display: none;"></td>
        <td type="residList" data-value="{{info.residList}}" style="display: none;"></td>
        <td type="personcount" data-value="{{info.personcount}}" style="display: none;"></td>
        <td>
            <button op="editDataOne" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}"><?php echo Enum_Lang::getPageText('system', 'edit'); ?></button>
            <button op="editResList" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}">物品管理</button>
            <?php foreach ($hotelLanguageList as $index => $language) { ?>
                <button op="editArticle" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}" data-type="<?php echo Enum_Article::ARTICLE_TYPE_ROOMTYPE; ?>_<?php echo $index + 1; ?>" data-article="{{info.detailLang<?php echo $index + 1; ?>}}"><?php echo Enum_Lang::getPageText('system', 'article'); ?>（<?php echo Enum_Lang::getPageText('language', $language); ?>）</button>
            <?php } ?>
        </td>
    </tr>
    {{/each}}
</script>
