<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo Enum_Lang::getPageText('room', 'roomTypeEditTitle'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="listEditor">
                    <input type="hidden" id="edit_id" value="0">
                    <div class="control-group" op="editFiled">
                        <?php $filedName = 'room';
                        $filedTitle = Enum_Lang::getPageText('room', 'roomNo'); ?>
                        <label class="control-label" for="edit_<?php echo $filedName; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <input type="text" id="edit_<?php echo $filedName; ?>" placeholder="<?php echo $filedTitle; ?>" class="span3" data-title="<?php echo $filedTitle; ?>">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <?php $filedName = 'typeid';
                        $filedTitle = Enum_Lang::getPageText('room', 'typeTitle'); ?>
                        <label class="control-label" for="edit_<?php echo $filedName; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <select id="edit_<?php echo $filedName; ?>" data-title="<?php echo $filedTitle; ?>">
                                <?php foreach ($roomTypeList as $roomType) { ?>
                                    <option value="<?php echo $roomType['id']; ?>"><?php echo $roomType['title_lang1']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <?php $filedName = 'floor';
                        $filedTitle = Enum_Lang::getPageText('room', 'roomFloor'); ?>
                        <label class="control-label" for="edit_<?php echo $filedName; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <select id="edit_<?php echo $filedName; ?>" data-title="<?php echo $filedTitle; ?>">
                                <?php foreach ($floorList as $floor) { ?>
                                    <option value="<?php echo $floor['id']; ?>"><?php echo $floor['floor']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <?php $filedName = 'size';
                        $filedTitle = Enum_Lang::getPageText('room', 'roomSize'); ?>
                        <label class="control-label" for="edit_<?php echo $filedName; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <input type="number" step="0.01" id="edit_<?php echo $filedName; ?>" placeholder="<?php echo $filedTitle; ?>" class="span2" data-title="<?php echo $filedTitle; ?>">
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveListData"
                        data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>"><?php echo Enum_Lang::getPageText('system', 'save'); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'><?php echo Enum_Lang::getPageText('system', 'close'); ?></button>
            </div>
        </div>
    </div>
</div>
