<div class="modal hide fade yulong" id="optionEditor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo Enum_Lang::getPageText('feedback', 'editOption'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="optionEditorList">
                </form>
                <button type="button" class="btn btn-primary" id='createOption' style="margin-left: 115px;"><?php echo Enum_Lang::getPageText('feedback', 'optionCreate'); ?></button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveOption" data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>"><?php echo Enum_Lang::getPageText('system', 'save'); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'><?php echo Enum_Lang::getPageText('system', 'close'); ?></button>
            </div>
        </div>
    </div>
</div>
<script type="text/html" id="optionEditorList_tpl">
    {{each optionList as option index}}
    <div class="control-group" op="editFiled">
        <label class="control-label">选项（拖动排序）：</label>
        <div class="controls">
            <input type="text" op="optionInput" class="span8" value="{{option}}"/>
            <span class="f14" style="display: inline-block; vertical-align: middle;">
                <em class="fr clearCity" op="deleteOption"></em>
            </span>
        </div>
    </div>
    {{/each}}
</script>