<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo Enum_Lang::getPageText('feedback', 'editTitle'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="listEditor">
                    <input type="hidden" id="edit_id" value="0">
                    <div class="control-group" op="editFiled">
                        <?php $filedName = 'listid';
                        $filedTitle = Enum_Lang::getPageText('feedback', 'listname'); ?>
                        <label class="control-label" for="edit_<?php echo $filedName; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <select id="edit_<?php echo $filedName; ?>" data-title="<?php echo $filedTitle; ?>">
                                <?php foreach ($feedbackList as $feedback) { ?>
                                    <option value="<?php echo $feedback['id']; ?>"><?php echo $feedback['name']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <?php $filedName = 'question';
                        $filedTitle = Enum_Lang::getPageText('feedback', 'question'); ?>
                        <label class="control-label" for="edit_<?php echo $filedName; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <input type="text" id="edit_<?php echo $filedName; ?>" placeholder="<?php echo $filedTitle; ?>" class="span8" data-title="<?php echo $filedTitle; ?>">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled" id="questionTypeEdit" style="display: none;">
                        <?php $filedName = 'type';
                        $filedTitle = Enum_Lang::getPageText('feedback', 'questionType'); ?>
                        <label class="control-label" for="edit_<?php echo $filedName; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <select id="edit_<?php echo $filedName; ?>" data-title="<?php echo $filedTitle; ?>">
                                <?php foreach (Enum_Feedback::getFeedbackQuestionTypeNameKey() as $typeId => $nameKey) { ?>
                                    <option value="<?php echo $typeId; ?>"><?php echo Enum_Lang::getPageText('feedback', $nameKey); ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <?php $filedName = 'sort';
                        $filedTitle = Enum_Lang::getPageText('feedback', 'questionSort'); ?>
                        <label class="control-label" for="edit_<?php echo $filedName; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <input type="number" id="edit_<?php echo $filedName; ?>" placeholder="<?php echo $filedTitle; ?>" class="span1" data-title="<?php echo $filedTitle; ?>">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <?php $filedName = 'status';
                        $filedTitle = Enum_Lang::getPageText('feedback', 'status'); ?>
                        <label class="control-label" for="edit_<?php echo $filedName; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <select id="edit_<?php echo $filedName; ?>" data-title="<?php echo $filedTitle; ?>">
                                <option value="0"><?php echo Enum_Lang::getPageText('feedback', 'disable'); ?></option>
                                <option value="1"><?php echo Enum_Lang::getPageText('feedback', 'enable'); ?></option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveListData"
                        data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>"><?php echo Enum_Lang::getPageText('system', 'save'); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'><?php echo Enum_Lang::getPageText('system', 'close'); ?></button>
            </div>
        </div>
    </div>
</div>
