<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/jquery-ui-1.8.22.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'feedbackQuestion'); ?>
                        <button id="createData" class="btn btn-info" style="margin-left: 5px;" type="button" data-toggle="modal" data-target="#editor"><?php echo Enum_Lang::getPageText('system', 'create'); ?>
                        </button>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/feedback/question_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('feedback', 'listname'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('feedback', 'question'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('feedback', 'questionType'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('feedback', 'questionSort'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('feedback', 'status'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('system', 'option'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/feedback/question_edit.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/feedback/question_option.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        checkParams: '<?php echo json_encode(Enum_Feedback::getFeedbackMustInput());?>',
        listUrl: '/feedbackajax/getQuestionList',
        createUrl: '/feedbackajax/createQuestion',
        updateUrl: '/feedbackajax/updateQuestion'
    };
</script>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/zh-CN.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/jquery-ui.min.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/feedback/question.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="listid" data-value="{{info.listid}}">{{info.listShow}}</td>
        <td type="question" data-value="{{info.question}}">{{info.question}}</td>
        <td type="type" data-value="{{info.type}}">{{info.typeShow}}</td>
        <td type="sort" data-value="{{info.sort}}">{{info.sort}}</td>
        <td type="status" data-value="{{info.status}}">{{info.statusShow}}</td>
        <td>
            <button op="editDataOne" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}"><?php echo Enum_Lang::getPageText('system', 'edit'); ?></button>
            {{if info.type != <?php echo Enum_Feedback::QUESTION_TYPE_INPUT ?>}}
            <button op="editOption" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}" data-option='{{info.option}}'><?php echo Enum_Lang::getPageText('feedback', 'editOption'); ?></button>
            {{/if}}
        </td>
    </tr>
    {{/each}}
</script>
