<div class="hero-unit hero-unit-custom hero-unit-mgdbtm clearfix" id="listFilter">
    <form class="form-horizontal">
        <div class="control-group control-group-block">
            <div class="pull-left control-item">
                <span class="control-label">ID：</span>
                <div class="controls">
                    <input id="userid" data-paramkey='id' type="number" class="form-control input-medium" op="filterCase" value=''/>
                </div>
            </div>
            <div class="pull-left control-item">
                <span class="control-label"><?php echo Enum_Lang::getPageText('feedback', 'question'); ?>：</span>
                <div class="controls">
                    <input id="filter_question" data-paramkey='question' type="text" class="form-control input-medium" op="filterCase"/>
                </div>
            </div>
            <div class="pull-left control-item">
                <span class="control-label"><?php echo Enum_Lang::getPageText('feedback', 'questionType'); ?>：</span>
                <div class="controls">
                    <select id="filter_type" data-paramkey='type' class=" input-medium select-long" op="filterCase">
                    <option value="all"><?php echo Enum_Lang::getPageText('system', 'all'); ?></option>
                    <option value="1"><?php echo Enum_Lang::getPageText('feedback', 'questionTypeInput'); ?></option>
                    <option value="2"><?php echo Enum_Lang::getPageText('feedback', 'questionTypeSelect'); ?></option>
                    <option value="3"><?php echo Enum_Lang::getPageText('feedback', 'questionTypeMuilt'); ?></option>
                    </select>
                </div>
            </div>
            <div class="pull-left control-item">
                <span class="control-label"><?php echo Enum_Lang::getPageText('feedback', 'listname'); ?>：</span>
                <div class="controls">
                    <select id="filter_listid" data-paramkey='listid' class="input-medium select-long" op="filterCase">
                        <option value="all"><?php echo Enum_Lang::getPageText('system', 'all'); ?></option>
                        <?php foreach ($feedbackList as $feedback) { ?>
                            <option value="<?php echo $feedback['id']; ?>"><?php echo $feedback['name']; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="pull-left control-item">
                <span class="control-label"><?php echo Enum_Lang::getPageText('feedback', 'status'); ?>：</span>
                <div class="controls">
                    <select id="filter_status" data-paramkey='status' class="input-medium select-long" op="filterCase">
                        <option value="all"><?php echo Enum_Lang::getPageText('system', 'all'); ?></option>
                        <option value="0"><?php echo Enum_Lang::getPageText('feedback', 'disable'); ?></option>
                        <option value="1"><?php echo Enum_Lang::getPageText('feedback', 'enable'); ?></option>
                    </select>
                </div>
            </div>
            <button id="searchBtn" class="mgtop5 pull-left btn btn-primary" type="button" data-loading-text="<?php echo Enum_Lang::getPageText('system', 'searching'); ?>">
                <?php echo Enum_Lang::getPageText('system', 'search'); ?>
            </button>
        </div>
    </form>
</div>
