<!DOCTYPE HTML>
<html>
<head>
<?php include($webConfig['layoutPath'].'/common/meta.phtml')?>
    <script src="<?php echo $webConfig['imgDomain']; ?>js/common/switch_hotel.js" type="text/javascript"></script>

</head>
<body>
<?php include($webConfig['layoutPath'].'/common/header.phtml')?>
<div class="container container-main" >
    <div class="row-fluid">
    <?php include($webConfig['layoutPath'].'/common/nav.phtml')?>
    </div>
</div>
</body>
</html>