<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'gsmorder'); ?>
                    </h1>
                </div>

                <div class="cont-mod">
                   <iframe src="<?php echo $serviceUrl;?>" width="80%" height="700px"></iframe>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>
