<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/jquery.searchableSelect.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'shoppingOrder'); ?>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/shopping/order_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th></th>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('shopping', 'createTime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('shopping', 'room'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('shopping', 'shopping'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('shopping', 'SHOPPINGCOUNT'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('shopping', 'shoppingStatus'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('shopping', 'orderAdmin'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('shopping', 'robotstatus'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/service/robot_deliver.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        listUrl: '/shoppingajax/getOrderList',
        callRobot: '/service/callRobot',
        deliverRobot: '/service/deliverRobot',
    };
</script>

<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/zh-CN.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/service/order.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/jquery.searchableSelect.js"></script>
<script>
    $(function() {
        $('.searchableSelect').searchableSelect();
    });
</script>

</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td><input type="checkbox" value="{{info.id}}" class="robotShopping"></td>
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="createtime" data-value="{{info.createtime}}">{{info.createtime}}</td>
        <td>{{info.userRoom}}</td>
        <td>{{info.shopping}}</td>
        <td type="count" data-value="{{info.count}}">{{info.count}}</td>
        <td>{{info.status}}</td>
        <td>{{info.admin}}</td>
        <td>{{info.robotstatusname}}</td>
    </tr>
    {{/each}}
</script>