<div class="hero-unit hero-unit-custom hero-unit-mgdbtm clearfix" id="listFilter">
    <form class="form-horizontal" style="width: 102%;">
        <div class="control-group control-group-block">
            <div class="pull-left control-item">
                <span class="control-label">ID：</span>
                <div class="controls">
                    <input id="avtivityUserId" data-paramkey='id' type="number" class="form-control input-medium"
                           op="filterCase" value=''/>
                </div>
            </div>

            <div class="pull-left control-item">
                <span class="control-label"><?php echo Enum_Lang::getPageText('shopping', 'ROOM'); ?>：</span>
                <div class="controls">
                    <select id="filter_room" data-paramkey='room' class="input-medium select-long" op="filterCase">
                        <option value=""><?php echo Enum_Lang::getPageText('system', 'all'); ?></option>
                        <?php foreach ($roomPositionList as $position) { ?>
                            <option value="<?php echo $position['position']; ?>"><?php echo $position['position']; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="pull-left control-item">
                <span class="control-label"><?php echo Enum_Lang::getPageText('robot', 'robotSendStatus'); ?>：</span>
                <div class="controls">
                    <select id="filter_status" data-paramkey='status' class="input-medium select-long" op="filterCase">
                        <option value="all"><?php echo Enum_Lang::getPageText('system', 'all'); ?></option>
                        <?php foreach ($statusList as $id => $name) { ?>
                            <option value="<?php echo $id; ?>"><?php echo $name; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <button id="searchBtn" class="mgtop5 pull-left btn btn-primary" type="button"
                    data-loading-text="<?php echo Enum_Lang::getPageText('system', 'searching'); ?>">
                <?php echo Enum_Lang::getPageText('system', 'search'); ?>
            </button>

            <button class="btn-primary btn mgtop5" id="deliverRobot"
                    style="margin-left: 10px;"><?php echo Enum_Lang::getPageText('robot', 'robotGet'); ?></button>


        </div>
    </form>
</div>
