<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/jquery.searchableSelect.css"/>

</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'robotGuide'); ?>
                    </h1>
                </div>

                <div class="hero-unit hero-unit-custom hero-unit-mgdbtm clearfix" id="listFilter">
                    <form class="form-horizontal">
                        <div class="control-group control-group-block">

                            <div class="pull-left control-item">
                                <span class="control-label"><?php echo Enum_Lang::getPageText('service', 'roomGuide'); ?>：</span>
                                <div class="controls">
                                    <select id="edit_dest" class="searchableSelect">
                                        <?php foreach ($roomPositionList as $row) { ?>
                                            <option value="<?php echo $row['id']; ?>" class="span3"><?php echo htmlentities($row['position']); ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                            <button id="searchBtn" class="mgtop5 pull-left btn btn-primary" type="button"
                                    data-loading-text="<?php echo Enum_Lang::getPageText('service', 'guide'); ?>">
                                <?php echo Enum_Lang::getPageText('service', 'guide'); ?>
                            </button>
                        </div>
                    </form>

                    <form class="form-horizontal">
                        <div class="control-group control-group-block">

                            <div class="pull-left control-item">
                                <span class="control-label"><?php echo Enum_Lang::getPageText('service', 'elevatorGuide'); ?>：</span>
                                <div class="controls">
                                    <select id="edit_dest" class="searchableSelect">
                                        <?php foreach ($floorPositionList as $row) { ?>
                                            <option value="<?php echo $row['id']; ?>" class="span3"><?php echo htmlentities($row['position']); ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                            <button id="searchBtn" class="mgtop5 pull-left btn btn-primary" type="button"
                                    data-loading-text="<?php echo Enum_Lang::getPageText('service', 'guide'); ?>">
                                <?php echo Enum_Lang::getPageText('service', 'guide'); ?>
                            </button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/jquery.searchableSelect.js"></script>
<script>
    $(function() {
        $('.searchableSelect').searchableSelect();
    });
</script>
</body>
</html>
