<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'appRss'); ?>
                        <button id="createData" class="btn btn-info" style="margin-left: 5px;" type="button"><?php echo Enum_Lang::getPageText('system', 'create'); ?>
                        </button>
                    </h1>
                </div>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('app', 'rssName'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('app', 'rss'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('app', 'rssType'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('system', 'option'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/app/rss_edit.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        listUrl: '/appajax/getHotelRssList',
        rssUrl: '/appajax/getRssList',
        updateUrl: '/appajax/updateHotelRssList'
    };
</script>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/app/rss.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="name" data-value="{{info.name}}">{{info.name}}</td>
        <td type="rss" data-value="{{info.rss}}">
            {{if info.rss}}
            <a href="{{info.rss}}" target="_blank">
                {{info.rss}}
            </a>
            {{/if}}
        </td>
        <?php if (Enum_Lang::getSystemLang() == Enum_Lang::LANG_KEY_CHINESE) { ?>
            <td type="typename" data-value="{{info.typename}}">{{info.typename}}</td>
        <?php } else { ?>
            <td type="typeenname" data-value="{{info.typeenname}}">{{info.typeenname}}</td>
        <?php } ?>
        <td>
            <button op="deleteRss" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}"><?php echo Enum_Lang::getPageText('system', 'delete'); ?></button>
        </td>
    </tr>
    {{/each}}
</script>
