<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo Enum_Lang::getPageText('app', 'insertRss'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <?php include($webConfig['layoutPath'] . '/app/rssList_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('app', 'rssName'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('app', 'rss'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('app', 'rssType'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('system', 'option'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="rssList"></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script id="rssList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="name" data-value="{{info.name}}">{{info.name}}</td>
        <td type="rss" data-value="{{info.rss}}">
            {{if info.rss}}
            <a href="{{info.rss}}" target="_blank">
                {{info.rss}}
            </a>
            {{/if}}
        </td>
        <td type="typename" data-value="{{info.typename}}">{{info.typename}}</td>
        <td>
            <button op="createRes" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}"><?php echo Enum_Lang::getPageText('system', 'create'); ?></button>
        </td>
    </tr>
    {{/each}}
</script>
