<div class="hero-unit hero-unit-custom hero-unit-mgdbtm clearfix" id="listFilter">
    <form class="form-horizontal">
        <div class="control-group control-group-block">
            <div class="pull-left control-item">
                <span class="control-label">ID：</span>
                <div class="controls">
                    <input id="userid" data-paramkey='id' type="number" class="form-control input-medium" op="filterCase" value=''/>
                </div>
            </div>
            <div class="pull-left control-item">
                <span class="control-label"><?php echo Enum_Lang::getPageText('activity', 'tagTitle'); ?>：</span>
                <div class="controls">
                    <select id="filter_typeid" data-paramkey='typeid' class="input-medium select-long" op="filterCase">
                        <?php foreach ($rssTypeList as $type) { ?>
                            <option value="<?php echo $type['id']; ?>"><?php echo $type['title']; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <button id="searchBtn" class="mgtop5 pull-left btn btn-primary" type="button"
                    data-loading-text="<?php echo Enum_Lang::getPageText('system', 'searching'); ?>">
                <?php echo Enum_Lang::getPageText('system', 'search'); ?>
            </button>
        </div>
    </form>
</div>
