<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/jquery-ui-1.8.22.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'appShare'); ?>
                    </h1>
                </div>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table style="width:48%;float: left;" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th><?php echo Enum_Lang::getPageText('app', 'enable'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="enableDataList" op="shareList"></tbody>
                                </table>
                                <table style="width:48%;float: left;margin-left: 4%;" class="table table-striped table-bordered table-hover fl">
                                    <thead>
                                    <tr>
                                        <th><?php echo Enum_Lang::getPageText('app', 'disable'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="disableDataList" op="shareList"></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <button type="button" style="margin-top: 20px;display: none;" class="fr btn btn-warning" id="saveShareData" data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>"><?php echo Enum_Lang::getPageText('system', 'save'); ?></button>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        hotelid: '<?php echo $hotelId;?>',
        listUrl: '/appajax/getShareList',
        updateUrl: '/appajax/updateShare'
    };
</script>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/jquery-ui.min.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/app/share.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    <tr {{if shareList.length}}style="display:none;" {{/if}} id='emptyShare'>
    <td style="height: 1px;"></td>
    </tr>
    {{each shareList as share}}
    <tr data-key="{{share.key}}" op="shareOne">
        <td>{{share.title}}</td>
    </tr>
    {{/each}}
</script>
