<div class="modal hide fade yulong" id="staffListEditor" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true" mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo Enum_Lang::getPageText('nav', 'appStaff'); ?></h4>
            </div>
            <div class="modal-body" id="detailBodyt" mf="modalfix">
                <form class="form-horizontal" id="staffEditorList">
                    <table>
                        <tr>
                            <td></td>
                            <td>
                                <button class="week btn btn-info" data-week="week1" type="button">周一</button>
                            </td>
                            <td>
                                <button class="week btn btn-info" data-week="week2" type="button">周二</button>
                            </td>
                            <td>
                                <button class="week btn btn-info" data-week="week3" type="button">周三</button>
                            </td>
                            <td>
                                <button class="week btn btn-info" data-week="week4" type="button">周四</button>
                            </td>
                            <td>
                                <button class="week btn btn-info" data-week="week5" type="button">周五</button>
                            </td>
                            <td>
                                <button class="week btn btn-info" data-week="week6" type="button">周六</button>
                            </td>
                            <td>
                                <button class="week btn btn-info" data-week="week7" type="button">周日</button>
                            </td>
                        </tr>
                        <?php
                            for($hour = 0; $hour<24; $hour++){
                                $output = sprintf("
                        <tr>
                            <td>%1\$02d:00-%1\$02d:59</td>
                            <td style='text-align: center'><input op=\"edit_staffList\" type=\"checkbox\" name=\"1%1$02d\" value=\"1%1$02d\" class='week1'></td>
                            <td style='text-align: center'><input op=\"edit_staffList\" type=\"checkbox\" name=\"2%1$02d\" value=\"2%1$02d\" class='week2'></td>
                            <td style='text-align: center'><input op=\"edit_staffList\" type=\"checkbox\" name=\"3%1$02d\" value=\"3%1$02d\" class='week3'></td>
                            <td style='text-align: center'><input op=\"edit_staffList\" type=\"checkbox\" name=\"4%1$02d\" value=\"4%1$02d\" class='week4'></td>
                            <td style='text-align: center'><input op=\"edit_staffList\" type=\"checkbox\" name=\"5%1$02d\" value=\"5%1$02d\" class='week5'></td>
                            <td style='text-align: center'><input op=\"edit_staffList\" type=\"checkbox\" name=\"6%1$02d\" value=\"6%1$02d\" class='week6'></td>
                            <td style='text-align: center'><input op=\"edit_staffList\" type=\"checkbox\" name=\"7%1$02d\" value=\"7%1$02d\" class='week7'></td>
                        </tr>
                                ", $hour);
                                echo $output;
                            }

                        ?>
                    </table>
                    <table style="position: absolute; top: 4%; right: 4%;">
                        <tr>
                            <td>
                                <button type="button" class="btn btn-info"><input type="checkbox" op="edit_staffWashing"
                                                                                  id="edit_staffWashing"><label style="display: inline-block"
                                            for="edit_staffWashing">洗衣服务推送设置</label></button>
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveStaffList" data-loading-text="保存中...">保存
                </button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'>关闭</button>
            </div>
        </div>
    </div>
</div>
