<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'shoppingOrderProcess'); ?>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/shopping/order_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <input type="hidden" value="<?php echo $userId;?>" id="current_userid">
                                <input type="hidden" value="<?php echo $userName;?>" id="current_username">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('shopping', 'createTime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('shopping', 'room'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('shopping', 'shopping'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('shopping', 'SHOPPINGCOUNT'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('shopping', 'shoppingStatus'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('shopping', 'orderAdmin'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('shopping', 'orderMemo'); ?></th>
                                        <th>操作</th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        listUrl: '/shoppingajax/getOrderList',
        updateUrl: '/shoppingOrderAjax/updateShoppingOrder'
    };
</script>

<?php include($webConfig['layoutPath'] . '/shopping/order_edit.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/zh-CN.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/service/order-process.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="createtime" data-value="{{info.createtime}}">{{info.createtime}}</td>
        <td>{{info.userRoom}}</td>
        <td>{{info.shopping}}</td>
        <td type="count" data-value="{{info.count}}">{{info.count}}</td>
        <td type="status" data-value="{{info.statusid}}">{{info.status}}</td>
        <td type="adminid" data-value="{{info.adminid}}">{{info.admin}}</td>
        <td type="memo" data-value="{{info.memo}}">{{info.memo}}</td>
        <td>
            <button op="editDataOne" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}">修改</button>
        </td>
    </tr>
    {{/each}}
</script>
