<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
     mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"
                    id="myModalLabel"><?php echo Enum_Lang::getPageText('nav', 'shoppingOrderProcess'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="listEditor">
                    <input type="hidden" id="edit_id" value="0">
                    <input type="hidden" id="edit_ordersproductsid" value="0">

                    <div class="control-group" op="editFiled">
                        <label class="control-label"
                               for="edit_productstatus"><?php echo Enum_Lang::getPageText('shopping', 'productStatus'); ?>
                            ：</label>
                        <div class="controls">
                            <select id="edit_productstatus" data-paramkey='productstatus' class="input-medium select-long"
                                    op="filterCase">
                                <?php foreach ($statusList as $id => $name) {
                                    ?>
                                    <option value="<?php echo $id; ?>"><?php echo $name; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>

                    <div class="control-group" op="editFiled">
                        <label class="control-label"
                               for="edit_adminid"><?php echo Enum_Lang::getPageText('shopping', 'orderAdmin'); ?>
                            ：</label>
                        <div class="controls">
                            <input type="text" id="edit_memo" data-paramkey="memo">
                        </div>
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveListData"
                        data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>"><?php echo Enum_Lang::getPageText('system', 'save'); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal"
                        id='closeEditor'><?php echo Enum_Lang::getPageText('system', 'close'); ?></button>
            </div>
        </div>
    </div>
</div>
