<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'hotelFloor'); ?>
                        <button id="createData" class="btn btn-info" style="margin-left: 5px;" type="button"
                                data-toggle="modal" data-target="#editor"><?php echo Enum_Lang::getPageText('system', 'create'); ?>
                        </button>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/hotel/floor_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('hotel', 'floor'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('hotel', 'floorPic'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('hotel', 'status'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('system', 'option'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/hotel/floor_edit.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        checkParams: '<?php echo json_encode(Enum_Hotel::getFloorMustInput());?>',
        listUrl: '/hotelajax/getFloorList',
        createUrl: '/hotelajax/createFloor',
        updateUrl: '/hotelajax/updateFloor',
    };
</script>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/hotel/floorList.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="floor" data-value="{{info.floor}}">{{info.floor}}</td>
        <td type="pic" data-value="{{info.pic}}">
            {{if info.pic}}
            <a href="{{info.pic}}" target="_blank">
                <img src="{{info.pic}}" style="max-width: 100px;max-height: 100px;"/>
            </a>
            {{/if}}
        </td>
        <td type="status" data-value="{{info.status}}">{{info.statusShow}}</td>
        <td>
            <button op="editDataOne" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}"><?php echo Enum_Lang::getPageText('system', 'edit'); ?></button>
            <?php foreach ($hotelLanguageList as $index => $language) { ?>
                <button op="editArticle" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}" data-type="<?php echo Enum_Article::ARTICLE_TYPE_FLOOR; ?>_<?php echo $index + 1; ?>" data-article="{{info.detailLang<?php echo $index + 1; ?>}}"><?php echo Enum_Lang::getPageText('system', 'article'); ?>（<?php echo Enum_Lang::getPageText('language', $language); ?>）</button>
            <?php } ?>
        </td>
    </tr>
    {{/each}}
</script>
