<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo Enum_Lang::getPageText('hotel', 'PANORAMICEDITTITLE'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="listEditor">
                    <input type="hidden" id="edit_id" value="0">
                    <?php foreach ($hotelLanguageList as $index => $language) { ?>
                        <?php $filedName = 'titleLang'; ?>
                        <?php $filedTitle = Enum_Lang::getPageText('hotel', 'panormaicTitle') . '（' . Enum_Lang::getPageText('language', $language) . '）'; ?>
                        <?php $filedIndex = $index + 1; ?>
                        <div class="control-group" op="editFiled">
                            <label class="control-label" for="edit_<?php echo $filedName . $filedIndex; ?>"><?php echo $filedTitle; ?>：</label>
                            <div class="controls">
                                <input type="text" id="edit_<?php echo $filedName . $filedIndex; ?>" placeholder="<?php echo $filedTitle; ?>" class="span3" data-title="<?php echo $filedTitle; ?>">
                            </div>
                        </div>
                    <?php } ?>
                    <div class="control-group" op="editFiled">
                        <?php $filedName = 'panoramic';
                        $filedTitle = Enum_Lang::getPageText('hotel', 'panormaicUrl'); ?>
                        <label class="control-label" for="edit_<?php echo $filedName; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <input type="text" id="edit_<?php echo $filedName; ?>" placeholder="<?php echo $filedTitle; ?>" class="span8" data-title="<?php echo $filedTitle; ?>">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <?php $filedName = 'pic';
                        $filedTitle = Enum_Lang::getPageText('hotel', 'panormaicPic'); ?>
                        <label class="control-label" for="edit_<?php echo $filedName; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <img src="" id="edit_<?php echo $filedName; ?>_show" style="max-height: 80px;"/>
                            <input type="file" id="edit_<?php echo $filedName; ?>" placeholder="<?php echo $filedTitle; ?>" class="span4" data-title="<?php echo $filedTitle; ?>" accept="<?php echo implode(",", $allowTypeImage); ?>">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <?php $filedName = 'status';
                        $filedTitle = Enum_Lang::getPageText('hotel', 'status'); ?>
                        <label class="control-label" for="edit_<?php echo $filedName; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <select id="edit_<?php echo $filedName; ?>" data-title="<?php echo $filedTitle; ?>">
                                <option value="0"><?php echo Enum_Lang::getPageText('hotel', 'disable'); ?></option>
                                <option value="1"><?php echo Enum_Lang::getPageText('hotel', 'enable'); ?></option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveListData"
                        data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>"><?php echo Enum_Lang::getPageText('system', 'save'); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'><?php echo Enum_Lang::getPageText('system', 'close'); ?></button>
            </div>
        </div>
    </div>
</div>
